version: "3"

services:
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./docker
    container_name: ${APP_NAME}-php
    working_dir: /var/www/
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
#    depends_on:
#      - db

#  db:
#    image: postgres:${DB_VERSION}-alpine
#    container_name: ${APP_NAME}-db
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_DB: ${DB_DATABASE}
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./var/pgsql/data:/var/lib/postgresql/data:rw

#  adminer:
#    image: adminer
#    container_name: ${APP_NAME}-adminer
#    environment:
#      ADMINER_DESIGN: konya
#      ADMINER_DEFAULT_SERVER: db
#    ports:
#      - "8080:8080"