version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poker-node
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - "8001:5173"