version: "3.7"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poker-node
    volumes:
      - .:/app
    restart: always
    ports:
      - "801:801"