<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVLvdoyN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVLvdoyN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVLvdoyN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVLvdoyN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVLvdoyN\App_KernelDevDebugContainer([
    'container.build_hash' => 'VLvdoyN',
    'container.build_id' => '14bd87f5',
    'container.build_time' => 1679681978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVLvdoyN');
