<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQPxWph\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQPxWph/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQPxWph.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQPxWph\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIQPxWph\App_KernelDevDebugContainer([
    'container.build_hash' => 'IQPxWph',
    'container.build_id' => '3e078af2',
    'container.build_time' => 1678201134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQPxWph');
