<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUu0f2dy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUu0f2dy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUu0f2dy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUu0f2dy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUu0f2dy\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uu0f2dy',
    'container.build_id' => '9175afec',
    'container.build_time' => 1679062193,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUu0f2dy');
